language: go
go:
  - '1.10'

sudo: false

before_install:
  - export TZ='Asia/Shanghai'
  - go get github.com/stretchr/testify

install:
  - go get ./fds/

script:
  - make test
  - make lint

matrix:
  allow_failures:
    - go: master
